$('#btnRegisterSwap').on('click', function(){
    $('#divLogin').slideToggle(function(){
        $('#divRegister').slideToggle();
    })
})
$('#btnReturnLogin').on('click',function(){
    $('#divRegister').slideToggle(function(){
        $('#divLogin').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})
$('#btnLogin').on('click',function(){
    $('#divLoginAndRegistration').slideToggle(function(){
        $('#divDashboard').slideToggle();
    })
})